// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwrR5hZcR8-9uqRnC0e6oSE6TXFIUHcnw',
    appId: '1:333882785080:web:8fc944230931b6d47f95cd',
    messagingSenderId: '333882785080',
    projectId: 'kawach-38226',
    authDomain: 'kawach-38226.firebaseapp.com',
    storageBucket: 'kawach-38226.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJG4EcOaYJZC7SbHkemkQxpCicGFz61g',
    appId: '1:333882785080:android:3493f8be624f28ab7f95cd',
    messagingSenderId: '333882785080',
    projectId: 'kawach-38226',
    storageBucket: 'kawach-38226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Lmy9E09Iya0gIH-XCFK7jE6nfntgaWQ',
    appId: '1:333882785080:ios:9e3d044aa345e5297f95cd',
    messagingSenderId: '333882785080',
    projectId: 'kawach-38226',
    storageBucket: 'kawach-38226.firebasestorage.app',
    iosBundleId: 'com.example.testRaitNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Lmy9E09Iya0gIH-XCFK7jE6nfntgaWQ',
    appId: '1:333882785080:ios:9e3d044aa345e5297f95cd',
    messagingSenderId: '333882785080',
    projectId: 'kawach-38226',
    storageBucket: 'kawach-38226.firebasestorage.app',
    iosBundleId: 'com.example.testRaitNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwrR5hZcR8-9uqRnC0e6oSE6TXFIUHcnw',
    appId: '1:333882785080:web:e4692afcca9a975a7f95cd',
    messagingSenderId: '333882785080',
    projectId: 'kawach-38226',
    authDomain: 'kawach-38226.firebaseapp.com',
    storageBucket: 'kawach-38226.firebasestorage.app',
  );
}
